### ISSUE TITLE
Uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by danieljgp2** [unimodules/react-native-unimodules#101]
Hi, im getting this error when i try to build on Android

> /Users/user/Documents/app/node_modules/expo-app-loader-provider/android/src/main/java/expo/loaders/provider/AppLoaderProvider.java:
> uses unchecked or unsafe operations.
> Recompile with -Xlint:unchecked for details.

Im using rn 0.61.x

**Comment by sjchmiela** [comment]
Hey @danieljgp2, this is not an error. 🙂 It's just a warning (even though it may be printed in red).

**Comment by shawwal** [comment]
> Hey @danieljgp2, this is not an error. 🙂 It's just a warning (even though it may be printed in red).

@sjchmiela but the apps can't be build in Android ? how can I fix this?

**Comment by sjchmiela** [comment]
The `uses unchecked or unsafe operations` does not cause the Android project not to compile, there must some another issue with the project.

See the screenshot below where a build has both that warning and finishes successfully:

![Zrzut ekranu 2020-06-15 o 09 02 29](https://user-images.githubusercontent.com/1151041/84627355-14ed5d00-aee7-11ea-92c1-b9ab04830f80.png)
