### ISSUE TITLE
Error: Unrecognized persmission: location

### ISSUE THREAD

**Issue by vvscode** [unimodules/react-native-unimodules#102]
It's a bare reacts native project.

Code I'm using: 

```js
import * as unimodules from 'react-native-unimodules';

// ...
    unimodules.Permissions.getAsync(unimodules.Permissions.LOCATION)
      .then(console.info)
      .catch(console.error);
```

version in `package.json`
```json
    "react-native-unimodules": "^0.7.0",
```

in `yarn.lock`

```
expo-permissions@~8.0.0:
  version "8.0.0"
  resolved "https://registry.yarnpkg.com/expo-permissions/-/expo-permissions-8.0.0.tgz#5a45e8451dd7ff37c9e6ce5e2447818372547813"
  integrity sha512-GHTRmwh1rd1b0FcibluPFu93NNQyl9b1anBBDVPmomoo9Prz7kDcO5p2hFqM99r896yvAUSe0fPloPKUq4g/1A==
```

save error about some other permission type (`Permissions.NOTIFICATIONS` works fine, while `Permissions.CAMERA` does not)

**Comment by vvscode** [comment]
My extended question is here https://stackoverflow.com/questions/59541610/expo-permissions-error-unrecognized-persmission-location

**Comment by ericyip** [comment]
Ran into same issue yesterday. turn out I have expo@35 in other package.
Be sure you don't have other version included.
try `yarn why expo-permissions`

**Comment by vvscode** [comment]
solved with `expo-location`

**Comment by sjchmiela** [comment]
Given https://github.com/unimodules/react-native-unimodules/issues/102#issuecomment-570587010, closing issue. 🙂
