### ISSUE TITLE
[EXLocation]No known instance method for selector 'hasGrantedPermission:'

### ISSUE THREAD

**Issue by chloeXu96** [unimodules/react-native-unimodules#116]
After upgrading` react-native-unimodules `from 0.5.0 to 0.7.0 and doing a pod update I am receiving the following error:
![WechatIMG21527](https://user-images.githubusercontent.com/50382750/75566974-b32fe280-5a1e-11ea-8989-e7f02c4bd9dc.png)

**Comment by sjchmiela** [comment]
Is the issue still relevant? When upgrading `react-native-unimodules` to `0.7.0` it would be best to also upgrade `expo-location` to matching version, that is `8.0.0`. Could you please try that? You can see that `8.0.0` version will have different code where the error is happening:

https://github.com/expo/expo/blob/102922fe6330af0ec439dc926e77897b72612705/packages/expo-location/ios/EXLocation/EXLocation.m#L223-L232

I think if you upgraded the code it would start to work. BTW we also added a `expo upgrade` command that should help you not encounter this kind of issues again. Sorry for it!
