### ISSUE TITLE
Project with path ':unimodules-app-loader' could not be found in project

### ISSUE THREAD

**Issue by sezginriggs** [unimodules/react-native-unimodules#122]
I upgraded my react-native-unimodules to 0.8.0 from 0.7.0-rc.4 (react-native 0.61.4) and now when building for Android, I'm getting these errors.

> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/Users/xyz/Desktop/mypath/ProjectName/node_modules/@unimodules/core/unimodules-core.gradle' line: 21
> 
> * What went wrong:
> A problem occurred evaluating project ':unimodules-react-native-adapter'.
> > Project with path ':unimodules-app-loader' could not be found in project ':unimodules-react-native-adapter'.

What might be the reason for this? Tried to remove node_modules and yarn.lock and install all from scratch but didn't help.

**Comment by brentvatne** [comment]
this is resolved on the latest version
