### ISSUE TITLE
Question: which default modules can be safely excluded?

### ISSUE THREAD

**Issue by ziyoshams** [unimodules/react-native-unimodules#123]
Currently `react-native-unimodules` comes with these modules out of the box:
```
expo-app-loader-provider
expo-constants
expo-file-system
expo-permissions
unimodules-barcode-scanner-interface
unimodules-camera-interface
unimodules-constants-interface
unimodules-core
unimodules-face-detector-interface
unimodules-file-system-interface
unimodules-font-interface
unimodules-image-loader-interface
unimodules-permissions-interface
unimodules-react-native-adapter
unimodules-sensors-interface
unimodules-task-manager-interface
```

  - Does anyone know what `unimodules-*` do?
  - Can they be excluded?
  - Can all of them be excluded except `core`?

Thanks!

**UPDATE**
In the recent React Native EU 2020 @brentvatne mentioned that these modules are very small header files and they don't impact the size of the app that much.

**Comment by ManigandanRaamanathan** [comment]
@ziyoshams any update on this issues? i'm facing same problem

**Comment by ziyoshams** [comment]
@ManigandanRaamanathan so far I have excluded this much without any issues:
```
[
    'expo-file-system', 
    'expo-app-loader-provider', 
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
]
```

**Comment by Ashoat** [comment]
My understanding is that the "interface" ones are small and used for cross-unimodule communication, but I also don't fully understand when they are necessary or how much space in the app bundle/binary they take up. I opened up #133 before realizing it's a duplicate of this.

**Comment by Aung-Myint-Thein** [comment]
> @ManigandanRaamanathan so far I have excluded this much without any issues:
> 
> ```
> // "react-native-unimodules": "^0.7.0"
> 
> [
>     'expo-file-system', 
>     'expo-app-loader-provider', 
>     'unimodules-face-detector-interface',
>     'unimodules-file-system-interface',
>     'unimodules-sensors-interface',
>     'unimodules-task-manager-interface',
>     'unimodules-barcode-scanner-interface',
>     'unimodules-camera-interface',
> ]
> ```

Would you mind to share the excluding lines you put in build.gradle? Currently, I am excluding only face-dector as following:

`addUnimodulesDependencies([exclude: ['expo-face-detector']])`

By the way, I have included unimodules in my RN bare project for expo-av. iOS is working fine in both dev and release. Android is working fine on dev but my release apk is crashing upon start with following error. Mind to help me take a look? Do you need to change anything to your index.js file to include `registerRootComponent` or something from expo?

![Screenshot 2020-09-07 at 2 42 20 PM](https://user-images.githubusercontent.com/612366/92364115-8fa9cb00-f118-11ea-8ba1-0b78944e0057.png)

**Comment by ziyoshams** [comment]
@Aung-Myint-Thein I am not sure why you have the error like that. Here is my exclusion, and I hope it helps: 

**ANDROID:**
```
dependencies {
    ...
    addUnimodulesDependencies([
        exclude: [
            'expo-file-system', 
            'expo-permissions', 
            'expo-app-loader-provider', 
            'unimodules-face-detector-interface',
            'unimodules-file-system-interface',
            'unimodules-font-interface',
            'unimodules-image-loader-interface',
            'unimodules-permissions-interface',
            'unimodules-sensors-interface',
            'unimodules-task-manager-interface',
            'unimodules-barcode-scanner-interface',
            'unimodules-camera-interface',
        ]
    ])
    ...
}
```

**iOS:**
```
target 'YOUR_APP' do
 ...
  use_unimodules!(exclude: [
    'expo-file-system', 
    'expo-app-loader-provider', 
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
  ])
end
```

**Comment by Aung-Myint-Thein** [comment]
Thanks! I found the issue 🙂  it is caused by an update in Sentry..

**Comment by ziyoshams** [comment]
My primary concern was the app size increase based on these modules. But, recent talk by @brentvatne in React Native EU 2020 indicates that these modules don't impact the size of the app.
