### ISSUE TITLE
`exclude` option doesn't work

### ISSUE THREAD

**Issue by gavrix** [unimodules/react-native-unimodules#127]
For iOS, documentation suggests some modules that are not used can be excluded from being installed in Cocoapods. Even the example from documentation does'n work
https://github.com/unimodules/react-native-unimodules/blob/master/README.md#L37

from providing following list of modules to be excluded: 
```
 use_unimodules!(exclude:[
    'expo-face-detector',
    'expo-camera',
    'expo-barcode-scanner',
    'expo-font',
    'expo-permissions',
    'expo-sensors',
    'expo-task',
    'expo-image-loader'
  ])
```

only `EXFont` and `EXPermissions` actually got excluded in resulting Podfile.lock, all other dependencies were installed.

**Comment by maderesponsively** [comment]
@gavrix I'm doing the following...

  use_unimodules!(exclude: [
    'unimodules-face-detector-interface',
    'unimodules-camera-interface',
    'unimodules-barcode-scanner-interface',
    'unimodules-sensors-interface',
  ])

**Comment by gavrix** [comment]
yeah, it's confusing. some modules have `unimodules` prefix, some `expo`.

**Comment by ManigandanRaamanathan** [comment]
@gavrix @maderesponsively for both android and iOs we need to use `unimodules` as prefix instead of `expo` and need to use `interface` as suffix?

**Comment by ManigandanRaamanathan** [comment]
@gavrix @maderesponsively @gavrix is this correct? in android and pod file

use_unimodules!(
    exclude: [
      'expo-face-detector',
      'expo-ads-admob',
      'expo-analytics-amplitude',
      'expo-app-auth',
      'expo-asset',
      'expo-barcode-scanner',
      'expo-battery',
      'expo-brightness',
      'expo-calendar',
      'expo-cellular',
      'expo-contacts',
      'expo-crypto',
      'expo-document-picker',
      'expo-error-recovery',
      'expo-file-system',
      'expo-font',
      'expo-gl',
      'expo-haptics',
      'expo-image-manipulator',
      'expo-intent-launcher',
      'expo-keep-awake',
      'expo-local-authentication',
      'expo-localization',
      'expo-mail-composer',
      'expo-media-library',
      'expo-network',
      'expo-print',
      'expo-random',
      'expo-analytics-segment',
      'expo-sms',
      'expo-sqlite',
      'expo-web-browser'
    ]
  )

**Comment by annelorraineuy** [comment]
Also having trouble excluding modules. 
`app/build.gradle`
```
addUnimodulesDependencies([exlude: [
          'expo-constants',
          'expo-file-system',
          'expo-asset',
          'expo-image-loader',
          'unimodules-font-interface',
          'unimodules-file-system-interface',
          'unimodules-face-detector-interface',
          'unimodules-constants-interface',
          'unimodules-camera-interface',
          'unimodules-barcode-scanner-interface',
  ]])
```
But still so many of these on the list are installed

**Comment by brentvatne** [comment]
@annelorraineuy - you wrote  `exlude` instead of `exclude` 😅
