### ISSUE TITLE
I got error when i used lib tfjs-react-native

### ISSUE THREAD

**Issue by duylinhdang1998** [unimodules/react-native-unimodules#131]
I use react-native 0.61.2 and I installed "@tensorflow/tfjs-react-native". But when I run-ios I got error like this. Help me please
![image](https://user-images.githubusercontent.com/40199004/78092646-7b8bd000-73fa-11ea-898c-4e689a9c5879.png)
Here my code 
![image](https://user-images.githubusercontent.com/40199004/78092664-85153800-73fa-11ea-9c47-7592f7544083.png)

**Comment by brentvatne** [comment]
ensure you have followed the setup instructions from the readme correctly. if you are just creating a new app i recommend using `npx create-react-native-app` to save yourself the trouble of having to follow those setup instructions
