### ISSUE TITLE
App crash in android version 0.9.0 and issue 'React/RCTImageLoaderProtocol.h' file not found with version 0.6.0

### ISSUE THREAD

**Issue by baotoan1905** [unimodules/react-native-unimodules#134]
Hello, 
I'm using react-native 0.60.0. When installing this library I got two issues
With version 0.9.0, in IOS I can't build since it return error ('React/RCTImageLoaderProtocol.h' file not found) so I have to revert it back to 0.6.0. But I got another issue in android with this version relate to androidX
When I install version 0.9.0, I cannot make it work in IOS and android either. In android, I can build but app crash when running.
Not sure how to go in this situation.

**Comment by tezqa** [comment]
Same here, i’m stuck between the 0.6.0 and the 0.9.0.

**Comment by baotoan1905** [comment]
@tezqa I managed to make it work in IOS by upgrading react-native to 0.61.x. Now I stuck with android since it still crash with the code I added in MainApplication.java, when I comment it out, it works as it used to be.
![image](https://user-images.githubusercontent.com/7258479/79448550-cff29a80-800b-11ea-972b-a7761cafa3dd.png)

**Comment by baotoan1905** [comment]
I figured out the root cause of crashing in android. It was because of the FastImage I'm using, I have to add this one in app/build.gradle. I guess unimodules is using glideModule so it conflicts with FastImage.
project.ext {
    excludeAppGlideModule = true
}

**Comment by brentvatne** [comment]
not sure how glide is related there, might be from another package.

here are the contents of the image-loader-interface:
https://github.com/expo/expo/blob/master/packages/unimodules-image-loader-interface/android/src/main/java/org/unimodules/interfaces/imageloader/ImageLoader.java
https://github.com/expo/expo/blob/master/packages/unimodules-image-loader-interface/android/build.gradle

**Comment by chrisbobbe** [comment]
It appears that the `Libraries/Image/RCTImageLoaderProtocol.h` file, in the React Native repo, didn't exist until https://github.com/facebook/react-native/commit/bf78d7969a48b63f7d57bf7cdb1b1d8af2f46e5c, which is tagged as released in RN v0.61.0.
