### ISSUE TITLE
App Store Connect : Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by samitha9125** [unimodules/react-native-unimodules#136]
Hi. I had to install react-native-unimodules because of expo-keepawake module. However in that installation, I mentioned in Podfile to remove few modules comes with unimodules including **expo-permissions**. 

```
use_unimodules!(exclude: [
    'expo-face-detector',
    'expo-constants',
    'expo-file-system',
    'expo-permissions',
    'expo-app-loader-provider',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface'
  ])
```

However in Pod installation, I saw that still excluded pods are getting installed. I didn't care that much until AppStore send me an email asking to turn on Push Notification Entitlement in XCode.

I don't use Push notifications in my app. But still Apple asks to Turn it on because of expo-permissions I assume. Can someone help me how to fix this issue without enabling push entitlement on XCode?

React native version : 0.61.5
react-native-unimodules : ^0.9.0

**Comment by ikhilko** [comment]
Hi there! I'm experiencing the same issue while started using `react-native-unimodules` in my react-native project.
React native version : 0.63.4
react-native-unimodules : 0.12.0
Maybe I'm wrong but looks like the root of issue Is because I'm using `#import <UMCore/UMAppDelegateWrapper.h>` as it's proposed in docs of unimodules.
Can anyone help me to understand is it possible to fix in app's codebase or I need to make a push notification entitlement? Thanks!

**Comment by gcourtemanche** [comment]
Same issue here, installed `react-native-unimodules` for `expo-keepawake` and got this email:


> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by AnthonyLabaere** [comment]
Same issue. I don't want t use push notification. How to "disable" it on expo ?
