### ISSUE TITLE
Unable to resolve module `@unimodules/core`

### ISSUE THREAD

**Issue by petekp** [unimodules/react-native-unimodules#14]
Metro is throwing this error when trying to use `expo-web-browser` in tandem with `react-native-unimodules`:
```sh
error: bundling failed: Error: Unable to resolve module `@unimodules/core` from `/Users/pete/code/testapp/node_modules/expo-web-browser/build/WebBrowser.js`: Module `@unimodules/core` does not exist in the Haste module map
```

The problem is solved by manually installing `@unimodules/core` despite this already being present as a dependency of `react-native-unimodules`.

**Comment by ZeeshanAhmadKhalil** [comment]
You mean using `npm install react-native-unimodules`  resolves the issue?
