### ISSUE TITLE
Execution failed for task ':unimodules-react-native-adapter:compileDebugKotlin'

### ISSUE THREAD

**Issue by naody** [unimodules/react-native-unimodules#141]
After installing `react-native-unimodules` on a react-native bare-workflow. I get the following error:
`Execution failed for task ':unimodules-react-native-adapter:compileDebugKotlin'`

I see the following error on Android studio
```
node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (6, 33): Unresolved reference: HeadlessAppLoader
```

**Comment by sjchmiela** [comment]
Hey! Could you please run `yarn why @unimodules/core` (or `npm why` if that's your weapon of choice) in your project and post the output here? Also btw, updating to `react-native-unimodules@0.9.1` should fix the issue, what version are you using?

**Comment by naody** [comment]
@sjchmiela thanks for the quick response.  Below is the `yarn why @unimodules/core` output. BTW like you said updating to `react-native-unimodules@0.9.1` fixed the issue. Thanks!
```
yarn why v1.19.1
[1/4] 🤔  Why do we have the module "@unimodules/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@unimodules/core@5.1.2"
info Reasons this module exists
   - "react-native-unimodules" depends on it
   - Hoisted from "react-native-unimodules#@unimodules#core"
info Disk size without dependencies: "500KB"
info Disk size with unique dependencies: "524KB"
info Disk size with transitive dependencies: "524KB"
info Number of shared dependencies: 1
✨  Done in 0.95s.
```

**Comment by sjchmiela** [comment]
Hm… output before upgrading to `react-native-unimodules` would be more useful 😃, but I'm really glad you fixed the problem already! 🎉

**Comment by naody** [comment]
@sjchmiela, the output was captured before the upgrade. Sorry if I've confused you on my comment.

**Comment by sjchmiela** [comment]
Ah, sorry, I thought I was being smart. 😅 I thought that `yarn why` would show another (apart from `react-native-unimodules`) dependency using `@unimodules/core` that required a newer version of `@unimodules/core` (this would explain why the latest was used). I'm happy it's ok now!

**Comment by HappyBhalodiya** [comment]
Hello!! After installing `react-native-unimodules@0.9.1`.  I get the following error:
`Type-error: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')`

![Screenshot_20200720-114249](https://user-images.githubusercontent.com/46159757/87905591-97d17c80-ca7e-11ea-8cb2-6acfebe0ce6c.png)

**Comment by joao-vieira** [comment]
Hello, I had this same problem in the version `^0.11.0` (react-native: `^0.63.2`).

Following the first comments, I tried to use [npm-why](https://www.npmjs.com/package/npm-why) and here's the output:
```shell
$ npm-why @unimodules/core

  Who required @unimodules/core:

  myapp > react-native-unimodules > @unimodules/core@5.5.0
```

Could it be the same question?

**Comment by nero2009** [comment]
Similar to @joao-vieira I am using expo barebone setup(react native: `~0.63.3` and react-native-unimodules: `~0.11.0`)
and I am getting this error `Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.`

Yarn why returns the below:
```
➜ git:(master) ✗ yarn why @unimodules/core
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@unimodules/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@unimodules/core@5.5.1"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#@unimodules#core"
   - Hoisted from "react-native-unimodules#@unimodules#core"
info Disk size without dependencies: "1.13MB"
info Disk size with unique dependencies: "1.15MB"
info Disk size with transitive dependencies: "1.15MB"
info Number of shared dependencies: 1
✨  Done in 1.12s.
```

Please how can I resolve this @sjchmiela

**Comment by mariomurrent-softwaresolutions** [comment]
> Similar to @joao-vieira I am using expo barebone setup(react native: `~0.63.3` and react-native-unimodules: `~0.11.0`) and I am getting this error `Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.`
> 
> Yarn why returns the below:
> 
> ```
> ➜ git:(master) ✗ yarn why @unimodules/core
> yarn why v1.22.4
> [1/4] 🤔  Why do we have the module "@unimodules/core"...?
> [2/4] 🚚  Initialising dependency graph...
> [3/4] 🔍  Finding dependency...
> [4/4] 🚡  Calculating file sizes...
> => Found "@unimodules/core@5.5.1"
> info Reasons this module exists
>    - "expo" depends on it
>    - Hoisted from "expo#@unimodules#core"
>    - Hoisted from "react-native-unimodules#@unimodules#core"
> info Disk size without dependencies: "1.13MB"
> info Disk size with unique dependencies: "1.15MB"
> info Disk size with transitive dependencies: "1.15MB"
> info Number of shared dependencies: 1
> ✨  Done in 1.12s.
> ```
> 
> Please how can I resolve this @sjchmiela

Did you solve the issue?

**Comment by Neosoulink** [comment]
> Similar to @joao-vieira I am using expo barebone setup(react native: `~0.63.3` and react-native-unimodules: `~0.11.0`) and I am getting this error `Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.`
> 
> Yarn why returns the below:
> 
> ```
> ➜ git:(master) ✗ yarn why @unimodules/core
> yarn why v1.22.4
> [1/4] 🤔  Why do we have the module "@unimodules/core"...?
> [2/4] 🚚  Initialising dependency graph...
> [3/4] 🔍  Finding dependency...
> [4/4] 🚡  Calculating file sizes...
> => Found "@unimodules/core@5.5.1"
> info Reasons this module exists
>    - "expo" depends on it
>    - Hoisted from "expo#@unimodules#core"
>    - Hoisted from "react-native-unimodules#@unimodules#core"
> info Disk size without dependencies: "1.13MB"
> info Disk size with unique dependencies: "1.15MB"
> info Disk size with transitive dependencies: "1.15MB"
> info Number of shared dependencies: 1
> ✨  Done in 1.12s.
> ```
> 
> Please how can I resolve this @sjchmiela

Have the same issue, any update?

**Comment by mariomurrent-softwaresolutions** [comment]
After upgrades it seems to work now

**Comment by Neosoulink** [comment]
This is what the dependencies look like:
```js
"dependencies": {
  //..
  "expo": "~41.0.1",
  "react": "17.0.1",
  "react-native": "0.64.1",
  "react-native-unimodules": "~0.13.3",
  //...
},
```

and here is the error i get when i build for android:
```shell
...\node_modules\@unimodules\react-native-adapter\android\src\main\java\org\unimodules\adapters\react\services\CookieManagerModule.java:13: error: CookieManagerModule is not abstract and does not override abstract method invalidate() in NativeModule
public class CookieManagerModule extends ForwardingCookieHandler implements InternalModule, NativeModule {
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error



> Task :unimodules-react-native-adapter:compileReleaseJavaWithJavac FAILED



FAILURE: Build failed with an exception.



* What went wrong:
Execution failed for task ':unimodules-react-native-adapter:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org/



Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings



BUILD FAILED in 57m 38s
980 actionable tasks: 980 executed
```

Should I upgrade ``react-native-unimodules`` to fix the problem? @mariomurrent-softwaresolutions

**Comment by mariomurrent-softwaresolutions** [comment]
Actually I upgraded the Expo SDK to the latest version and removed the unimodales.

**Comment by mattreginaldo** [comment]
I have the same problem, even updating doesn't work...

**Comment by marchiartur** [comment]
same problem

**Comment by gramospear** [comment]
also having this exact same issue

**Comment by nikber84** [comment]
[public class CookieManagerModule extends ForwardingCookieHandler implements InternalModule, NativeModule](https://github.com/expo/fyi/blob/main/android-071-rc-build-failure.md)
Try this

**Comment by dylan-manchester** [comment]
Anyone find a workaround for this?
I'm running into the same problem while trying to upgrade RN from 64 to 65.

**Comment by wmthor** [comment]
I resolved it adding the following in `android/app/build.gradle`.

```gradle
def REACT_NATIVE_VERSION = new File(['node', '--print', "JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
}
```

**Comment by pranjalmd** [comment]
> This is what the dependencies look like:
> 
> ```js
> "dependencies": {
>   //..
>   "expo": "~41.0.1",
>   "react": "17.0.1",
>   "react-native": "0.64.1",
>   "react-native-unimodules": "~0.13.3",
>   //...
> },
> ```
> 
> and here is the error i get when i build for android:
> 
> ```shell
> ...\node_modules\@unimodules\react-native-adapter\android\src\main\java\org\unimodules\adapters\react\services\CookieManagerModule.java:13: error: CookieManagerModule is not abstract and does not override abstract method invalidate() in NativeModule
> public class CookieManagerModule extends ForwardingCookieHandler implements InternalModule, NativeModule {
> ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
> 
> > Task :unimodules-react-native-adapter:compileReleaseJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':unimodules-react-native-adapter:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org/
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 57m 38s
> 980 actionable tasks: 980 executed
> ```
> 
> Should I upgrade `react-native-unimodules` to fix the problem? @mariomurrent-softwaresolutions

I got the same issues during RN upgrade `64.4` => `66.5`.
We upgraded `react-native-unimodules` from `0.12.0` to `0.13.3` and got the above mentioned error.

After a little investigation, I found out that the method [onCatalystInstanceDestroy()](https://github.com/facebook/react-native/blob/v0.66.5/ReactAndroid/src/main/java/com/facebook/react/bridge/NativeModule.java#L55) is depricated and is replaced by [invalidate()](https://github.com/facebook/react-native/blob/v0.66.5/ReactAndroid/src/main/java/com/facebook/react/bridge/NativeModule.java#L58). 
Source: [react-native/blob/v0.66.5/.../NativeModule.java#L53](https://github.com/facebook/react-native/blob/v0.66.5/ReactAndroid/src/main/java/com/facebook/react/bridge/NativeModule.java#L53)

So I created a patch using [patch-package](https://www.npmjs.com/package/patch-package) and it worked for me!

```
diff --git a/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/services/CookieManagerModule.java b/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/services/CookieManagerModule.java
index c878fdd..684bda5 100644
--- a/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/services/CookieManagerModule.java
+++ b/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/services/CookieManagerModule.java
@@ -41,4 +41,9 @@ public class CookieManagerModule extends ForwardingCookieHandler implements Inte
   public void onCatalystInstanceDestroy() {
     // do nothing
   }
+
+  @Override
+  public void invalidate() {
+    // do nothing
+  }
 }

```
