### ISSUE TITLE
NativeUnimoduleProxy.viewManagersNames issue

### ISSUE THREAD

**Issue by zulkufadsiz** [unimodules/react-native-unimodules#142]
Hi. After bundling android app crashed and getting this error . TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames') error.
How can i fix this issue  ?
react-native:0.62.2 

![image](https://user-images.githubusercontent.com/16453694/81118910-6858ac80-8f32-11ea-95db-dfc1fa67eee3.png)

**Comment by Porcupine96** [comment]
In my case, I was missing a line:
```
self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
```

from:
https://gist.github.com/brentvatne/1ece8c32a3c5c9d0ac3a470460c65603#file-appdelegate-m-L14

that I think was recently added.

**Comment by Shadowtampa** [comment]
Well this is a _very_ ugly workaround but works in case youre desperate. Still trying to know the real problem.

1. Locate the file "NativeViewManagerAdapter.native.js" under "node_modules\expo-modules-core\build\NativeViewManagerAdapter.native.js"
2. Find the function "requireNativeViewManager(viewName)"
3. comment this portion of code:
`if (__DEV__) {
        const { NativeUnimoduleProxy } = NativeModules;
        if (!NativeUnimoduleProxy.viewManagersNames.includes(viewName)) {
            const exportedViewManagerNames = NativeUnimoduleProxy.viewManagersNames.join(', ');
            console.warn(`The native view manager required by name (${viewName}) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [${exportedViewManagerNames}].`);
        }
    }`

When debugging an application, I found out that "NativeUnimoduleProxy.viewManagersNames" was returning undefined, and then the "includes" function would fire an error.

**Comment by MarangoniEduardo** [comment]
I was having the same issue attempting to upgrade from the Expo SDK 42 to the SDK 45, with the explanation provided by @Shadowtampa I investigated further, and if you run:

`expo install expo-modules-core`

In 0.9.2, which is the latest its actually doing a different validation, which I presume fixed it:

` const { viewManagersMetadata } = NativeModules.NativeUnimoduleProxy;
    const viewManagerConfig = viewManagersMetadata?.[viewName];
    if (__DEV__ && !viewManagerConfig) {
        const exportedViewManagerNames = Object.keys(viewManagersMetadata).join(', ');
        console.warn(`The native view manager required by name (${viewName}) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [${exportedViewManagerNames}].`);
    }`

**Comment by m3h0w** [comment]
I'm dealing with the same problem and `expo install expo-modules-core` doesn't do it for me.

**Comment by kamilwezgowiec** [comment]
@m3h0w if you have a monorepo by any chance and are updating 1 project at a time, add `expo-modules-core` to all of them. Applying this to just one did not work for us.

**Comment by naidong-zhang** [comment]
> 3. comment this portion of code:

I commented this part of code but when I ran `npm run test` again, jest still told me the same error message:
> TypeError: Cannot read properties of undefined (reading 'includes')
> at requireNativeViewManager (node_modules/expo-modules-core/src/NativeViewManagerAdapter.native.tsx:28:49)

I am really confused.

**Comment by WNemencha** [comment]
Anyone found a solution to this one? Getting the same error message while running tests on a Expo app :/

```
 FAIL   CLIENT:REACT_NATIVE  src/payments/provider.spec.tsx
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'includes')

      at requireNativeViewManager (node_modules/expo-modules-core/src/NativeViewManagerAdapter.native.tsx:28:49)
      at Object.<anonymous> (node_modules/expo-av/src/ExponentVideo.tsx:3:16)
      at Object.<anonymous> (node_modules/expo-av/src/Video.tsx:18:1)
```

**Comment by sergiulucaci** [comment]
@m3h0w did you manage to make it work? 

I'm facing the same issue in a bare react native app - i've upgraded from unimodules, following all the steps, no error at build time but whenever I arrive at the screen that uses expo-av getting an issue related to `NativeUnimoduleProxy`.

```
Cannot read property 'viewManagersMetadata' of null
```

<img width="331" alt="Screen Shot 2022-07-14 at 5 24 07 PM" src="https://user-images.githubusercontent.com/16645155/179005842-73f1544c-47ef-44a7-905a-88098ea7cc76.png">

**Comment by hussein321** [comment]
> 

any update about this issue? did you fix it?
