### ISSUE TITLE
Incompatibilidade de projeto react-native CLI 

### ISSUE THREAD

**Issue by Ivandeclei** [unimodules/react-native-unimodules#143]
ao instalar o pacote apresenta o erro de compatibilidade com gradle 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by brentvatne** [comment]
I just initialized a new project with `npx react-native init` and followed the instructions in the README, it worked as expected.

https://github.com/brentvatne/testwithsixtwo
