### ISSUE TITLE
Install documentation - UMReactNativeAdapter not found

### ISSUE THREAD

**Issue by Thomazella** [unimodules/react-native-unimodules#144]
Followed ios install steps and got an error about `<UMReactNativeAdapter/UMModuleRegistryAdapter.h>` being missing.

fix was to add 2 lines to podfile https://stackoverflow.com/a/61282028/9189180

opening issue for awareness & discussion. Maybe we are missing these instructions? I'm using rn 0.62.2

would send readme PR but unfamiliar with project. :)

**Comment by brentvatne** [comment]
this is in the readme: https://github.com/unimodules/react-native-unimodules#-configure-ios

that section links out to https://gist.github.com/brentvatne/d093e440698404803bd9c29d962949b0/revisions#diff-4a25b996826623c4a3a4910f47f10c30 which shows you what to do
