### ISSUE TITLE
error: constructor ModuleRegistryAdapter in class ModuleRegistryAdapter cannot be applied to given types;       new ModuleRegistryAdapter(),       ^   required: ReactModuleRegistryProvider   found: no arguments   reason: actual and formal argument lists differ in length 5 errors  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by sha-zam** [unimodules/react-native-unimodules#145]
I’m trying to use react-native-unimodules for android. i followed all the steps but im getting the following error when running npm run android: 

<img width="668" alt="Screenshot 2020-05-16 at 12 53 25 PM" src="https://user-images.githubusercontent.com/50140351/82111042-99c44a00-9774-11ea-8083-b288d4b22ebb.png">

My MainApplication.java has a getPackages method that looks like this:

<img width="540" alt="Screenshot 2020-05-16 at 12 53 02 PM" src="https://user-images.githubusercontent.com/50140351/82111003-73061380-9774-11ea-9ce5-63bbc42527fb.png">

However, after I run npm run android,  a PackageList.java gets built that has a getPackages method that looks like this:

<img width="426" alt="Screenshot 2020-05-16 at 12 52 21 PM" src="https://user-images.githubusercontent.com/50140351/82111053-aea0dd80-9774-11ea-8f8d-ebcf4cc389c7.png">

Since the new ModuleRegistryAdapter() has no args it's throwing an error. It appears that the method is being overwritten and the implementation in MainApplication.java doesn't matter?

Can anyone pls help me find a solution? I really don't know what's 
wrong

**Comment by XeeshanAnsari** [comment]
Same issue with react-native 0.61.5.

**Comment by brentvatne** [comment]
follow the instructions from the readme and everything will go fine :)

notice that you're using` packages.add` - that won't work, you need to use `packages.addAll`.

see this from the readme: https://gist.github.com/mczernek/9de9e184abc430e9e3508d26738c8a14/revisions

**Comment by olivinesguerra** [comment]
not working...

**Comment by curiousdustin** [comment]
@brentvatne, as described by @sha-zam, what appears to be happening is that `PackageList.java` gets auto-generated with the code: `new ModuleRegistryAdapter()`. This fails because `ModuleRegistryAdapter()` is expecting 1 param instead of 0. How do we stop this line from being generated, or get it to generate properly? It seems unnecessary because we add the packages manually in `MainApplication.java`.

**Comment by curiousdustin** [comment]
Adding the following in `react-native.config.js` appears to allow my project to compile:

```
  dependencies: {
    '@unimodules/react-native-adapter': {
      platforms: {
        android: null,
      },
    },
  },
```

Although, I have not determined if this will cause other issues yet.

@brentvatne, Aside from this, I have followed the readme carefully, and it still gave this error. Which part of the instructions in the readme is supposed to be resolving this issue of mismatched number of constructor parameters?

**Comment by takahi5** [comment]
I have same issue as @curiousdustin .
My project was ejected from Expo SDK 37.

**Comment by sunilloharshoreline1** [comment]
The following worked for me:

1. Open the `MainApplication.java` of your application.

2. Add to the imports:

   import com.yourpackage.generated.BasePackageList;  // NOTE : Replace your package name with com.yourpackage rest .generated.BasePackageList; would be same 
   import org.unimodules.adapters.react.ModuleRegistryAdapter;
   import org.unimodules.adapters.react.ReactModuleRegistryProvider;
   import org.unimodules.core.interfaces.SingletonModule;

3. Remove mModuleRegistryProvider variable from `MainApplication.java` and replace it with  : 
private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());

4. Replace  getPackages() method with following : 
 @Override
 protected List<ReactPackage> getPackages() {
 @SuppressWarnings("UnnecessaryLocalVariable")
 List<ReactPackage> packages = new PackageList(this).getPackages();
 // Add unimodules
 List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
 new ModuleRegistryAdapter(mModuleRegistryProvider)
 );
 packages.addAll(unimodules);
 return packages;
 }

The `MainApplication.java` may look like this : 

package com.yourpackage;
import com.yourpackage.generated.BasePackageList;
import android.app.Application;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
 private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());

 private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
 @Override
 public boolean getUseDeveloperSupport() {
 return BuildConfig.DEBUG;
 }

 @Override
 protected List<ReactPackage> getPackages() {
 @SuppressWarnings("UnnecessaryLocalVariable")
 List<ReactPackage> packages = new PackageList(this).getPackages();
 // Add unimodules
 List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
 new ModuleRegistryAdapter(mModuleRegistryProvider)
 );
 packages.addAll(unimodules);
 return packages;
 }

 @Override
 protected String getJSMainModuleName() {
 return "index";
 }
 };

 @Override
 public ReactNativeHost getReactNativeHost() {
 return mReactNativeHost;
 }

 @Override
 public void onCreate() {
 super.onCreate();
 SoLoader.init(this, /* native exopackage */ false);
 }
}
