### ISSUE TITLE
Android build Failed with RN 0.59.1 with error import expo packages doesnot found

### ISSUE THREAD

**Issue by Sukumar-Abhijeet** [unimodules/react-native-unimodules#15]
error: package expo.adapters.react does not exist
import expo.adapters.react.ModuleRegistryAdapter;
package expo.adapters.react does not exist
import expo.adapters.react.ReactAdapterPackage;
 package expo.core.interfaces does not exist
import expo.core.interfaces.Package;
error: package expo.core.interfaces does not exist
import expo.core.interfaces.SingletonModule;

This is my MainApplication.java file
```


import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;


import expo.adapters.react.ModuleRegistryAdapter;
import expo.adapters.react.ReactAdapterPackage;
import expo.adapters.react.ReactModuleRegistryProvider;
import expo.core.interfaces.Package;
import expo.core.interfaces.SingletonModule;
import expo.modules.constants.ConstantsPackage;
import expo.modules.filesystem.FileSystemPackage;
import expo.modules.permissions.PermissionsPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
    new ReactAdapterPackage(),
    new ConstantsPackage(),
    new PermissionsPackage(),
    new FileSystemPackage()
 ), Arrays.<SingletonModule>asList());

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ModuleRegistryAdapter(mModuleRegistryProvider)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**Comment by tsapeta** [comment]
Hey, thanks for reporting an issue!
Have you run through the configuration guide correctly?
Do you have `includeUnimodulesProjects()` method call in your `settings.gradle` file and `addUnimodulesDependencies()` in `app/build.gradle`?

**Comment by Sukumar-Abhijeet** [comment]
Yes i have checked my files 
My settings.gradle file
apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects();
rootProject.name = '**********'

include ':app'


My app/build.gradle
apply plugin: "com.android.application"
apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
import com.android.build.OutputFile
..
...
....
dependencies {
    addUnimodulesDependencies()
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

**Comment by Sukumar-Abhijeet** [comment]
Can someone help me on this ??

**Comment by tsapeta** [comment]
Seems strange, I've created a blank RN project then installed and configured `react-native-unimodules` and it seems to work fine 🤔 
Could you check if building your project in Android Studio works? Also, what is the command that you execute in the command line to build it?

**Comment by tsapeta** [comment]
It turned out there was a problem with `react-native-unimodules` not supporting `react-native@0.59` correctly. Please check out my comment in another issue: https://github.com/unimodules/react-native-unimodules/issues/12#issuecomment-473911142

I hope this will fix your issue, but if not, feel free to reopen it.

**Comment by johnopthof** [comment]
Hi,

For me the yarn upgrade did not work.. Weird bc i have 
I followed steps stated above. I followed installation guide: https://github.com/unimodules/react-native-unimodules
Except the configure iOS part as I am running Windows..

react-native-cli: 2.0.1
react-native: 0.59.5

![Snag_1e3a23af](https://user-images.githubusercontent.com/11233133/56349486-f0093700-61c8-11e9-8f1c-3e024d563a8a.png)
![Snag_1e3c7cc2](https://user-images.githubusercontent.com/11233133/56349671-4bd3c000-61c9-11e9-8655-0095c6ca0657.png)

I think this was the last time i am hiding m path... :p

**Comment by Sukumar-Abhijeet** [comment]
U might need to downgrade the react native to 58 
Issues are there with 59 
Version 58 solved my similar issue 
Also readd the above comments

**Comment by johnopthof** [comment]
Thanks for your fast respons. But that did not work for me..

**Comment by Sukumar-Abhijeet** [comment]
What version of unimodule are you installing?? 
Try with 0.2.0

**Comment by johnopthof** [comment]
Still not working.. 

Unimodule 0.2.0 is installed by default.

(Again) I made a new project, and this is what i did:
> react-native init --version="react-native@0.58.0" kut	
> react-native run-android	
   WORKS

> npm install react-native-unimodules
*followed instructions* 	
> react-native run-android	
ERROR:
	internal/modules/cjs/loader.js:584
	throw err;
    	^
	Error: Cannot find module 'asap/raw'

> npm install
> react-native run-android	
	* What went wrong:
	Failed to capture snapshot of output files for task ':app:mergeDebugResources' property 'incrementalFolder' during up-to-date check.
	> Could not read path '
> npm install react-native@0.58.6	
> react-native run-android	
	* What went wrong:
	Failed to capture snapshot of output files for task ':app:transformClassesWithDexBuilderForDebug' property 'streamOutputFolder' during up-to-date check.
	> Could not read path

**Comment by Sukumar-Abhijeet** [comment]
There is the "could not read path error" .
Had u checked the installation guide properly?? 
If you coud make a repo of it and share. 
Would like to check it.

**Comment by johnopthof** [comment]
Yes, i followed the installation guide carefully. 

Do you want me to include node_modules?

**Comment by johnopthof** [comment]
This is it: https://github.com/johnopthof/unimodulesTest
I did not push node_modules. Let me know if you want me to.

**Comment by Sukumar-Abhijeet** [comment]
![WhatsApp Image 2019-04-20 at 2 51 20 AM](https://user-images.githubusercontent.com/35395038/56444767-ba269880-6317-11e9-8122-56313a255699.jpeg)
Everything seems to be fine.
I tested your unimodulesTest, no sign of error .
build was successful in a single build.
try doing once more with a new build

**Comment by MrPluto** [comment]
for me, i followed the instruction and then i get this error 
```
Script '/Users/tongchepluto/Desktop/cst/memuu_app/node_modules/react-native-unimodules/gradle.groovy' line: 74

* What went wrong:
A problem occurred evaluating project ':app'.
> You need to have MainApplication.java in your project
```
react native 0.57
react native unimodules 0.3.1

**Comment by arhamchoudhary** [comment]
just remove everything from /android/app/src/main/java/com/{your app name}/generated/BasePackageList.java

**Comment by narek11** [comment]
I am doing SDK 42 to 43 migration and deleting the `BasePackageList.java` fixed it!
