### ISSUE TITLE
The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly

### ISSUE THREAD

**Issue by MrXyfir** [unimodules/react-native-unimodules#158]
Copying from meedan/react-native-share-menu#84, which we use to create a share extension that loads part of our app within the host app to share content from that app to our own.

We implemented a share extension with this package and everything works fine except when we try to use certain Expo packages we receive the following error:

```
The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
Running "ShareMenuModuleComponent" with {"rootTag":1,"initialProps":{}}
[TypeError: undefined is not an object (evaluating '_ExpoContacts.default.requestPermissionsAsync')]
```

We noticed this issue first with expo-av, and then later for expo-contacts.

In the share extension portion of our `Podfile` we're loading unimodules the same way we do for our main app.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'OurAppName' do
	config = use_native_modules!

	use_react_native!(:path => config["reactNativePath"])
	use_unimodules!

	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	use_flipper!
	post_install do |installer|
		flipper_post_install(installer)
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
			end
		end
	end
end

target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'

  use_native_modules!
  use_unimodules!
end

```

What's the right way to import?

**Comment by sjchmiela** [comment]
Hey @MrXyfir! Are you sure you're providing unimodules to `RCTBridge`? What I mean is these lines:

https://github.com/expo/expo/blob/f9b34a3bc23515456c962785a2e9af569c1971eb/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.m#L47

https://github.com/expo/expo/blob/f9b34a3bc23515456c962785a2e9af569c1971eb/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.m#L78-L83

**Comment by MrXyfir** [comment]
Thanks for the response @sjchmiela! Yes, our `AppDelegate.m` contains those lines and the modules work in our main app. Do we need something similar for the share extension itself, since they are two different targets? I apologize, I know very little about Objective-C which I'm sure is my issue here...

Our share extension is essentially this:

**ShareExtension-Bridging-Header.h**
```
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTBridgeDelegate.h>
#import <React/RCTRootView.h>
```

**ShareViewController.h**
```
#ifndef ShareViewController_h
#define ShareViewController_h
#endif
```

**ShareViewController.m**
```
#import <Foundation/Foundation.h>
```

**Comment by sjchmiela** [comment]
That's really strange… I don't have experience with app extensions either. Is the `.m` file really just an import? Is there no `RCTBridge` initialization?

**Comment by MrXyfir** [comment]
@sjchmiela It's all magic to me... That's really all that's in the `.m` file, and after looking through the documentation again I'm not even sure it's supposed to be there.

- https://github.com/meedan/react-native-share-menu/blob/master/IOS_INSTRUCTIONS.md
- https://github.com/meedan/react-native-share-menu/blob/master/SHARE_EXTENSION_VIEW.md

I think it's linked somehow through `AppDelegate.m`. See the final section of `IOS_INSTRUCTIONS.md`.

**Comment by sjchmiela** [comment]
Ah, ok, looking at the setup instructions I can see that the share view controller implementation is actually located in [`ReactShareViewController.swift`](https://github.com/meedan/react-native-share-menu/blob/master/ios/ReactShareViewController.swift), which, if you look closely, does instantiate `RCTBridge` itself and it does include unimodules when bridge asks for extra modules. It looks like `react-native-share-menu` simply does not support unimodules (I understand why).

What you'd need to do to have unimodules installed in the share extension would be to create a subclass of `ReactShareViewController` and override the `extraModules(for bridge: RCTBridge)` method so it returns extra modules from `moduleRegistryAdapter`. Here's how we do this in `bare-expo`:

1. We hold a reference to `moduleRegistryAdapter` in the class:
  https://github.com/expo/expo/blob/fe1cc398b79528719c88ef4b82b74289117520a4/apps/bare-expo/ios/BareExpo/AppDelegate.swift#L17
2. When the particular class starts, `moduleRegistryAdapter` is instantiated:
  https://github.com/expo/expo/blob/fe1cc398b79528719c88ef4b82b74289117520a4/apps/bare-expo/ios/BareExpo/AppDelegate.swift#L24
3. Then we override `extraModules(for bridge)` method like:
  https://github.com/expo/expo/blob/fe1cc398b79528719c88ef4b82b74289117520a4/apps/bare-expo/ios/BareExpo/AppDelegate.swift#L86-L87
4. And simply return the modules:
  https://github.com/expo/expo/blob/fe1cc398b79528719c88ef4b82b74289117520a4/apps/bare-expo/ios/BareExpo/AppDelegate.swift#L101

**Comment by MrXyfir** [comment]
@sjchmiela Thank you for your time and help! I greatly appreciate it.

I don't have time right this second to try out your solution but it makes perfect sense and I assume it will fix my issue. You might hear from me again if I have any troubles but hopefully not!

**Comment by mabounassif** [comment]
This is not working on my side, the extensions do not support `sharedApplications` that is used in the `UMUtilities.m`. I suspect that you have disabled the only use APIs that are extension compatible, which means your app will be rejected by the App Store.

**Comment by MrXyfir** [comment]
@mabounassif We had no issue submitting to the App Store. We ended up forking the plugin to make the changes @sjchmiela mentioned above and it worked!

However we've since reworked our share extension to simply redirect the user to our app because with everything we were importing and trying to do within the share extension we kept hitting the 120 MB memory limit which would crash it randomly.
