### ISSUE TITLE
Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by nero2009** [unimodules/react-native-unimodules#159]
I recently scaffolded a new expo barebone application and I get the following error when I try to build an android release bundle
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.
> Could not resolve all artifacts for configuration ':unimodules-react-native-adapter:releaseCompileClasspath'.
   > Could not find react-native-0.63.3.jar (com.facebook.react:react-native:0.63.3).
```
This is what `yarn why @unimodules/core` return:

```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@unimodules/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@unimodules/core@5.5.1"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#@unimodules#core"
   - Hoisted from "react-native-unimodules#@unimodules#core"
info Disk size without dependencies: "1.13MB"
info Disk size with unique dependencies: "1.15MB"
info Disk size with transitive dependencies: "1.15MB"
info Number of shared dependencies: 1
✨  Done in 1.18s.
```
react-native : 0.63.3
react-native-unimodules: ~0.11.0

**Comment by sjchmiela** [comment]
Are you sure you have `react-native@0.63.3` installed? Does the `node_modules/react-native/android` directory exist? Is `build.gradle` configured to try to look for AARs (prebuilt Android dependencies in there, like: https://github.com/expo/expo/blob/f9b34a3bc23515456c962785a2e9af569c1971eb/templates/expo-template-bare-minimum/android/build.gradle#L25-L28)?

**Comment by nero2009** [comment]
I do have react native 0.63.3 installed and `build.gradle` is properly configured but I noticed there is no `react-native-0.63.3.jar` file in `node_modules/react-native/android` as seen below:
<img width="522" alt="Screenshot 2020-10-15 at 19 12 55" src="https://user-images.githubusercontent.com/29065069/96169858-b37fde00-0f1a-11eb-9761-1a537f9b0fba.png">

Could this be the cause

**Comment by sjchmiela** [comment]
Actually I think Gradle would look for `react-native-0.63.3.aar`, not `.jar`. Moreover, I noticed there is a similarly-named file — `.react-native-0.63.3.aar.icloud`. Is it possible that iCloud has synced this folder, uploaded the AAR to the cloud and left only a placeholder file?

**Comment by nero2009** [comment]
@sjchmiela thanks for pointing that out

> Moreover, I noticed there is a similarly-named file — `.react-native-0.63.3.aar.icloud`. Is it possible that iCloud has synced this folder, uploaded the AAR to the cloud and left only a placeholder file?

The problem was that the file was synced to icloud and only a placeholder existed. 
Thanks for the quick replies
