### ISSUE TITLE
TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')

### ISSUE THREAD

**Issue by max-docly** [unimodules/react-native-unimodules#162]
I am getting this error on ios with latest version of unimodules.

Has anyone ran into this issue?

```
WARN: The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly

ERROR: TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')
```

**Comment by Turkialmalki** [comment]
> I am getting this error on ios with latest version of unimodules.
> 
> Has anyone ran into this issue?
> 
> ```
> WARN: The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
> 
> ERROR: TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')
> ```

Hi @max-docly 

Did you solve this issue? If so, How did you solve it? 

Thanks!
