### ISSUE TITLE
README Instructions are slightly incorrect

### ISSUE THREAD

**Issue by AlexMachin1997** [unimodules/react-native-unimodules#17]
**Instructions:**
Add apply from: '../node_modules/react-native-unimodules/gradle.groovy' and then 'includeUnimodulesProjects()' to the top of android/settings.gradle

**Problem:**
The instructions provided are technically incorrect, you can't actually do it how the instructions outlined When the node_modules was included and then the method was added above it threw an invalid amount error. 

**Solution:**
To resolve the issue the node_modules were included and then the 'includeUnimodulesProjects()' was executed below, it then proceeded with the rest of the installation. It should like the example below:
```
apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects()

```
Please correct me if I'm wrong, it was just an issue for me and the instructions seemed incorrect.

Thanks,
Alex

**Comment by brentvatne** [comment]
thanks! the wording on here was definitely unclear, I changed it to this:

> - At the top of `android/settings.gradle`, add `apply from: '../node_modules/react-native-unimodules/gradle.groovy'` and then on the next line add `includeUnimodulesProjects()`.
