### ISSUE TITLE
unsupported, pod install --project-directory

### ISSUE THREAD

**Issue by ironforward** [unimodules/react-native-unimodules#18]
While not a major problem, I wanted to at least document this for any other users running into this issue.

It seems that unimodules assumes you are running ```pod install``` from the current working directory, which means ```pod install --project-directory=relativePath/``` does not work.

<img width="741" alt="Screen Shot 2019-03-22 at 3 59 41 PM" src="https://user-images.githubusercontent.com/7257376/54857290-be7d7880-4cbb-11e9-9fe9-d61a103e74e8.png">

Workaround: just change directory into the folder and run pod install there instead of using the ```--project-directory``` flag

<img width="583" alt="Screen Shot 2019-03-22 at 4 00 06 PM" src="https://user-images.githubusercontent.com/7257376/54857295-c210ff80-4cbb-11e9-9783-552b65bb673f.png">

**Comment by brentvatne** [comment]
didn't even know this was an option! interesting, thanks for letting us know
