### ISSUE TITLE
 RN version 0.66.1 install onsignal got this error Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by Chandara-97** [unimodules/react-native-unimodules#181]
Hi there !!
I want to use Onesignal then type this command line:
`"yarn add react-native-onesignal"`
I got this error:
`"Could not load RNOneSignal native module. Make sure native dependencies are properly linked."`
**My react native(CLI):**
`"react-native": "0.66.1",`

**Comment by kmkz-69** [comment]
Hi @Chandara-97 
I assume you are using expo
all you have to do is this command,
Add OneSignal by running yarn add react-native-onesignal
Link OneSignal with expo install react-native-onesignal

**Comment by Chandara-97** [comment]
Thanks @kmkz-69 !!
Do you have any conguration because I'm use CLI

**Comment by kmkz-69** [comment]
You don't need any configuration ,
first delete your node folder ,
 expo install react-native-onesignal
 expo install onesignal-expo-plugin  and check your app.json  if expo did or did not add the plugin you need to add it  ,"plugin":[  "onesignal-expo-plugin"]
