### ISSUE TITLE
[iOS] RNNavigation and Unimodules

### ISSUE THREAD

**Issue by bogdan0083** [unimodules/react-native-unimodules#19]
Hey guys! Thank you for giving us the opportunity to use expo packages in bare RN projects! ❤️

I'm using [React Native Navigation](https://wix.github.io/react-native-navigation/#/), my AppDelegate.m looks like this: 

```obj-c
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  return YES;
}

@end
```

Everything works fine but I want to integrate unimodules here. If I replace the code with [this diff](https://gist.github.com/brentvatne/94960dacb343310b76be9cc157d90049/revisions), obviously, React Native Navigation stops working.

As I understood from the RNN source code, It has a third optional argument:
```obj-c
[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions bridgeManagerDelegate:delegate]
```
It allows to add extra modules to an app, but I can't figure out what should I pass as an argument to that last `bridgeManagerDeleger` to make RNN + unimodules work together, can you please help me?

Lots of people using RNN these days, I think it would be cool to know how to make these two projects work together.

Thanks!

**Comment by brentvatne** [comment]
It looks like you just need to make your `AppDelegate` implement the `RNNBridgeManagerDelegate`, then provide the `AppDelegate` instance as the `bridgeManagerDelegate`. Let me know how this goes for you

**Comment by bogdan0083** [comment]
Alright, I found a solution. 

`AppDelegate.h` should be the same as in [this diff](https://gist.github.com/brentvatne/94960dacb343310b76be9cc157d90049/revisions)

Here's the working `AppDelegate.m`:
```obj-c
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions bridgeManagerDelegate:self];
  return YES;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge andExperience:nil];
  // You can inject any extra modules that you would like here, more information at:
  // https://facebook.github.io/react-native/docs/native-modules-ios.html#dependency-injection
  return extraModules;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
#ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

@brentvatne Thanks for your help! ❤️

Closing.

**Comment by brentvatne** [comment]
awesome, thank you for sharing that!
