### ISSUE TITLE
Conflicting documentation?

### ISSUE THREAD

**Issue by daryl** [unimodules/react-native-unimodules#20]
I'm wondering why in the `expo-app-auth` documentation it specifies to import the package as `import { AppAuth } from 'expo-app-auth'` when it says to set it up using this package. Yet in the documentation for this package it says to use this format `import * as AppAuth from 'expo-app-auth'`.

**Comment by brentvatne** [comment]
can you provide links? I don't see where it says `import * as AppAuth from 'expo-app-auth'` anywhere. 

- nope: https://docs.expo.io/versions/latest/sdk/app-auth/
- nope: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/app-auth.md

**Comment by daryl** [comment]
That's exactly my point, it doesn't say that! But that's what I need to do to make this work.

```
import { AppAuth } from 'expo-app-auth'
```

This doesn't work (`undefined`), however, this does:

```
import * as AppAuth from 'expo-app-auth'
```

The only reference to the format above I've seen is in the `react-native-unimodules` README.

**Comment by brentvatne** [comment]
ah, thanks! it seems that the import format is incorrect in the docs then, I’ll update tomorrow

**Comment by daryl** [comment]
Is this the case for all libraries you want to use from Expo through Unimodules?

**Comment by brentvatne** [comment]
not all, but most - https://github.com/expo/expo/blob/master/packages/expo/src/Expo.ts shows how they're imported in the `expo` package

**Comment by brentvatne** [comment]
updated docs in https://github.com/expo/expo/commit/9dbc7a3fef30b147d7a1ddd9aed0e8d4d0cce5fb, should be live soon
