### ISSUE TITLE
could not read script

### ISSUE THREAD

**Issue by Albert0405** [unimodules/react-native-unimodules#21]
Im trying to configure my settings on android unfortunately i encounter this problem. I checked the and compare my current settings to `expo-template-bare` app in its `Android` folder, all the same but i still have this problem below

```
Could not read script 'C:\Local D\ML Guide\MLGuide\android\node_modules\react-native-unimodules\gradle.groovy' as it does not exist.
```

**Comment by Albert0405** [comment]
Sorry my fault,

i copy pasted this `android/app/build.gradle`
`apply from: "../node_modules/react-native-unimodules/gradle.groovy"`

instead of this
`apply from: "../../node_modules/react-native-unimodules/gradle.groovy"`

**Comment by tsapeta** [comment]
Looks like the documentation is correct now, so I'm closing this issue 😉
