### ISSUE TITLE
error: package expo.adapters.react does not exist

### ISSUE THREAD

**Issue by johnopthof** [unimodules/react-native-unimodules#30]
Hi,

For me the yarn upgrade did not work.. (Posted in other issues) Weird bc i have 
I followed steps stated in these threads. I followed installation guide: https://github.com/unimodules/react-native-unimodules
Except the configure iOS part as I am running Windows..

react-native-cli: 2.0.1
react-native: 0.59.5

![Snag_1e3a23af](https://user-images.githubusercontent.com/11233133/56349486-f0093700-61c8-11e9-8f1c-3e024d563a8a.png)
![Snag_1e3c7cc2](https://user-images.githubusercontent.com/11233133/56349671-4bd3c000-61c9-11e9-8655-0095c6ca0657.png)

I think this was the last time i am hiding m path... :p

**Comment by brentvatne** [comment]
it should be org.unimodules.adapters.react

you can install the latest version of react-native-unimodules and try this, see https://gist.github.com/tsapeta/9e50a4c2c0083fe8e578959526bfbed3/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa from the readme
