### ISSUE TITLE
Manual Linking?

### ISSUE THREAD

**Issue by n8stowell82** [unimodules/react-native-unimodules#34]
Is there any chance of getting manual linking instructions for this library?  I try to avoid cocoapods at all costs as it usually causes me more problems than it fixes.  It would be really nice to have at least a bare set of needed dependencies to be added into Xcode instead of mandating use of cocoapods

**Comment by n8stowell82** [comment]
I should note that I am more than happy to help in the documentation process for this, I just need to know what exactly needs to be added to the Xcode project first.  Thanks!

**Comment by vincentgheza** [comment]
Hello,
I am also very interested in manually installing links in XCodes.

And I also wanted to know if it is possible to integrate this element with react-native 0.38.1?

**Comment by sibelius** [comment]
embrace cocoapods

it will be easier when autolink ship with v60

**Comment by tsapeta** [comment]
Right now we support CocoaPods as the only way to install unimodules in iOS projects. It would be a bit harder for us to maintain them as Xcode libraries and considering that React Native is now recommending CocoaPods and `react-native init` projects will use CocoaPods by default soon, I guess not supporting manual linking is not a big disadvantage.
