### ISSUE TITLE
package com.myapp.generated does not exist

### ISSUE THREAD

**Issue by allicanseenow** [unimodules/react-native-unimodules#35]
Copy everything from the tutorial for MainApplication.java. Here is the code:
```
import com.myapp.generated.BasePackageList;

import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;
```
It says "package com.myapp.generated does not exist". Is this a bug?

**Comment by MrPluto** [comment]
solutions?

**Comment by DeanIfalo** [comment]
@MrPluto
import com.myapp.generated.BasePackageList;
Path location "myapp" needs replacement.

**Comment by MrPluto** [comment]
@DeanIfalo aye man, and i still has [this](https://github.com/unimodules/react-native-unimodules/issues/15#issuecomment-495129326) issue and have no idea. could you help if possible？

**Comment by timothyerwin** [comment]
I had this issue for a second when I realized I didn't follow all the instructions on https://docs.expo.dev/bare/installing-unimodules/
