### ISSUE TITLE
No support to kotlin projects

### ISSUE THREAD

**Issue by geovannimp** [unimodules/react-native-unimodules#36]
I have a react native project with kotlin and unimodules is trying to find MainApplication.java giving me the following error:

```
You need to have MainApplication.java in your project
```

**Comment by MrPluto** [comment]
try `./gradlew clean` . it works for me

**Comment by tsapeta** [comment]
Kotlin support has been added here: https://github.com/unimodules/react-native-unimodules/pull/39
I've just published `react-native-unimodules@0.4.1` with this change 🙂 Let me know if you still have any issues.

**Comment by geovannimp** [comment]
Hey @tsapeta 

We still have issues with our kotlin project.

Line 77 from gradle.groovy is checking by `'**/MainApplication.java'` and we are using `MainApplication.kt`

Changing this should fix the issue
