### ISSUE TITLE
expo-sensor issue

### ISSUE THREAD

**Issue by dean9703111** [unimodules/react-native-unimodules#45]
I want to use expo-sensor, but when I use like this:
```
import { Sensors } from 'react-native-unimodules';
console.log(Sensors);
```
It will return "undefined".
But 
```
import { Permissions, Constants, FileSystem } from 'react-native-unimodules';
```
Would return the correct value.

I want to use sensor like devicemotion.
Thanks.

**Comment by tsapeta** [comment]
`react-native-unimodules` package exports only a few, the most common unimodules like Permissions, Constants and FileSystem. Other unimodules should be imported from its npm package name, it means you should import them this way:

```
import { DeviceMotion, Gyroscope, Magnetometer, Accelerometer } from 'expo-sensors';
```

You can also take a look at [`expo-sensors` index file](https://github.com/expo/expo/blob/master/packages/expo-sensors/src/index.ts), to check what exactly is being exported there.
