### ISSUE TITLE
Initially Android Camera permission is always denied

### ISSUE THREAD

**Issue by jpudysz** [unimodules/react-native-unimodules#5]
Build config:
```
"@unimodules/core": "0.2.1"
"expo-camera": "3.0.0",
"react-native": "0.58.6",

Real device: Samsung Galaxy J5, Android 8.1
Environment: development
```

*Side note: For iOS everything is working correctly*

**Issue**
Initially on Android `expo-permissions` always returns status = `denied`

**How to reproduce**
1. Install bare react native app with `unimodules` and `expo-camera`.
2. Link everything according to readmes
3. Add corresponding `uses-permission` to AndroidManifest
3. Use `Permissions.getAsync`

**Expected behaviour**
I should receive status = `UNDETRMINED` as I've never asked user for pormission (yet)

**Current behaviour**
status = `DENIED`

![permissions](https://user-images.githubusercontent.com/9088288/54116320-c4877580-43ee-11e9-8514-ad5f37839393.png)

**Comment by sjchmiela** [comment]
Hey! Could you please try adding `expo-permissions@4.0.1-beta.0` to your project and verifying if that has fixed your issue? https://github.com/expo/expo/pull/3819
