### ISSUE TITLE
does not work with react native 0.59.9 on android release APK

### ISSUE THREAD

**Issue by thanh90** [unimodules/react-native-unimodules#53]
everything is OK, except on release APK. expo-permissions only return never_ask_again, gradients don't work, image_picker said that _launchImageLibraryAsync_ function didn't exist on android

**Comment by felipecarvalho** [comment]
I have the same problem here.
A workaround to fix this is set "enableProguardInReleaseBuilds" to "false" on android/app/build.gradle

**Comment by LuckyLuke19** [comment]
Instead of disabling ProGuard as @felipecarvalho mentioned, you can add this line `-keep class expo.modules.permissions.** { *; }` in your `android/app/proguard-rules.pro` file. Disabling ProGuard would significantly increase your APK size.

**Comment by thanh90** [comment]
> Instead of disabling ProGuard as @felipecarvalho mentioned, you can add these lines
> 
> ```
> -keep class expo.modules.permissions.** { *; }
> -keep class expo.modules.imagepicker.** { *; }
> -keep class expo.modules.lineargradient.** { *; }
> ```
> 
> in your `android/app/proguard-rules.pro` file. This way, ProGuard will not be applied to these specific modules, but it will still be applied to all other files.

thank @LuckyLuke19 . this works for me. i got this error too when i upgraded to 34. don't know what happened
