### ISSUE TITLE
Does this package includes support for android x for all expo packages? 

### ISSUE THREAD

**Issue by shubhamdeol** [unimodules/react-native-unimodules#61]
Expo packages like, expo-permissions, expo-font etc
How can I make them work in react native version 0.6

**Comment by brentvatne** [comment]
use jetifier. we'll update them to use androidx without you needing to use jetifier in sdk36 (not the next sdk release, which will be sdk35 - this is focused on ios13 and some maintenance)

**Comment by dangrahn** [comment]
@brentvatne `expo-av` doesn't seem to support AndroidX (using jetifier) though, see https://github.com/expo/expo/issues/5310

**Comment by kesha-antonov** [comment]
Hey!
Any news about support of RN 0.60.+ ?

**Comment by dangrahn** [comment]
Related discussion here https://github.com/unimodules/react-native-unimodules/issues/62

**Comment by brentvatne** [comment]
works with 0.60+ and you can use jetifier for updating imports. jetifier should run by default anyhow on 0.60+
