### ISSUE TITLE
Update Installation Guide for React 0.60.x

### ISSUE THREAD

**Issue by sudomann** [unimodules/react-native-unimodules#62]
The [demonstrative Podfile linked in the install/setup instructions](https://gist.github.com/sjchmiela/6c079f2173938a9a61a7c6f053c45000) apparently uses an old format/syntax which does NOT work with React 0.60.x

**Comment by watanabeyu** [comment]
Hi @sudomann 
I have updated 0.59.8 -> 0.60.4.
So I noted the files at [this repository](https://github.com/watanabeyu/rn-update-repo), and [Podfile is here](https://github.com/watanabeyu/rn-update-repo/blob/iOS-v0.60.4/ios/Podfile).

**Comment by sudomann** [comment]
Much appreciated!

**Comment by dangrahn** [comment]
@sudomann @watanabeyu The suggested install instructions for React Native 0.60.x worked for me 👍. But how come this was closed without addressing a change to `master`?

**Comment by sudomann** [comment]
I'm sorry, if I remember correctly, I closed it because I had read somewhere in this repository that it's progression was tied to whatever version of React Native expo was on. Expo has not yet progressed to React Native 0.60.x, so technically, it is not sensible for this repo's maintainers to update instructions/code on `master ` to reflect an unsupported version of React Native.

In my opinion, since this repo is most useful to people using expo libraries without the expo sdk, it's progression should be tied to the development of React Native.

If I can find it again, I'll share a link/reference to

**Comment by dangrahn** [comment]
Thanks for the explanation @sudomann 

> In my opinion, since this repo is most useful to people using expo libraries without the expo sdk, it's progression should be tied to the development of React Native.

I agree!

**Comment by kesha-antonov** [comment]
> Thanks for the explanation @sudomann
> 
> > In my opinion, since this repo is most useful to people using expo libraries without the expo sdk, it's progression should be tied to the development of React Native.
> 
> I agree!

I agree too!

**Comment by kopax** [comment]
Just wondering... I have never tried expo and I am just noticing all the mess to upgrade.

Theoretically, If I start using react-native with expo 0.59.x will I be able to upgrade later to 0.60.x without breaking change?

**Comment by brentvatne** [comment]
i'm not sure what you mean @kopax. do are you referring to using react-native-unimodules in a bare react-native app or expo managed workflow?

also the previous comment is out of date, we have since updated the installation instructions for this package to explain how to use it on >= 0.60 in addition to older versions: https://github.com/unimodules/react-native-unimodules

**Comment by kopax** [comment]
Thanks. I am still not sure to understand. I have a new app to make and I need to have ios/android/web.

I wanted to use 0.60.0 but then noticed almost all boilerplate use older version. **react-native-dom** doesn't even work with 0.60.0. 
How did you manage to  use 0.60.0 on `react-native-unimodule` and with what library to build Web/Native ?

Do you have a clue if expo work with 0.60.0 ? I am hesitating between starting with RN 0.59.X and expo, react-native-web or no expo and RN 0.60.x. 

Maybe react-native-unimodules could help to write less native code if I go for the 2nd option. What do you think ? (I have poor background of native and react-native + react native web environment)

**Comment by brentvatne** [comment]
> Maybe react-native-unimodules could help to write less native code if I go for the 2nd option. What do you think ? (I have poor background of native and react-native + react native web environment)

yeah that's the idea.

> How did you manage to use 0.60.0 on react-native-unimodule and with what library to build Web/Native ?

you can initialize a new project with react-native-cli and install react-native-unimodules in it

> Do you have a clue if expo work with 0.60.0 ? I am hesitating between starting with RN 0.59.X and expo, react-native-web or no expo and RN 0.60.x.

managed expo is currently on 0.59 but we're in the process of updating to 0.61. we always update a bit behind upstream to give it a chance to stabilizing and so that we can ensure all of the libraries work

**Comment by kopax** [comment]
> you can initialize a new project with react-native-cli and install react-native-unimodules in it

But then I can't use expo, I can't use react-native-dom, so I should do all my UI from scratch ?

> managed expo is currently on 0.59 but we're in the process of updating to 0.61. we always update a bit behind upstream to give it a chance to stabilizing and so that we can ensure all of the libraries work

Or should I go with expo and react-native 0.59 ?

Just trying to get started with the best thinking. Thanks for your replies!
