### ISSUE TITLE
React Native 0.60.x Support

### ISSUE THREAD

**Issue by mirmajeed1** [unimodules/react-native-unimodules#67]
When will the React Native 0.60.x support be available?

**Comment by ThomasLarge** [comment]
Would be good to know when this is happening 👍

**Comment by ferrannp** [comment]
I'd like to know what is not working for the others on 0.60.x? I was trying to update my app, I had to apply a small patch on Android: https://github.com/ferrannp/fithero/blob/796d526b53ddb6a8363144b2b38ac5d1e2880835/patches/%40unimodules%2Breact-native-adapter%2B2.0.1.patch

Then my PR https://github.com/ferrannp/fithero/pull/125 seems to run ok on `0.60.5` using unimodules.

Am I missing something?

**Comment by kevinvangelder** [comment]
@ferrannp My project gives this error on iOS when replicating your changes: 
```
null is not an object (evaluating NativeUnimoduleProxy.viewManagersNames)
```
Are you able to run your project in iOS or just Android?

**Comment by brentvatne** [comment]
the latest version supports this and instructions for installation in readme are updated!
