### ISSUE TITLE
CocoaPods could not find compatible versions for pod "UMTaskManagerInterface":

### ISSUE THREAD

**Issue by lucianomlima** [unimodules/react-native-unimodules#70]
## Steps to reproduce

- Create a new react native app: `react-native init Example`
- Install Unimodule package: `yarn add react-native-unimodules`
- Change Podfile to enable unimodules and run `pod install`

<details>
  <summary>Error from pod install</summary>
  <pre>$ pod install
Installing unimodules:
 expo-app-loader-provider@7.0.0 from ../node_modules/expo-app-loader-provider/ios
 expo-constants@7.0.0 from ../node_modules/expo-constants/ios
 expo-file-system@7.0.0 from ../node_modules/expo-file-system/ios
 expo-permissions@7.0.0 from ../node_modules/expo-permissions/ios
 unimodules-barcode-scanner-interface@4.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@4.0.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@4.0.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@4.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@4.0.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@4.0.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@4.0.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@4.0.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@4.0.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.0.0-alpha.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@4.0.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@4.0.0 from ../node_modules/unimodules-task-manager-interface/ios

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `EXAppLoaderProvider` from `../node_modules/expo-app-loader-provider/ios`
Fetching podspec for `EXConstants` from `../node_modules/expo-constants/ios`
Fetching podspec for `EXFileSystem` from `../node_modules/expo-file-system/ios`
Fetching podspec for `EXPermissions` from `../node_modules/expo-permissions/ios`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native/`
Fetching podspec for `React-Core` from `../node_modules/react-native/React`
Fetching podspec for `React-DevSupport` from `../node_modules/react-native/React`
Fetching podspec for `React-RCTActionSheet` from `../node_modules/react-native/Libraries/ActionSheetIOS`
Fetching podspec for `React-RCTAnimation` from `../node_modules/react-native/Libraries/NativeAnimation`
Fetching podspec for `React-RCTBlob` from `../node_modules/react-native/Libraries/Blob`
Fetching podspec for `React-RCTImage` from `../node_modules/react-native/Libraries/Image`
Fetching podspec for `React-RCTLinking` from `../node_modules/react-native/Libraries/LinkingIOS`
Fetching podspec for `React-RCTNetwork` from `../node_modules/react-native/Libraries/Network`
Fetching podspec for `React-RCTSettings` from `../node_modules/react-native/Libraries/Settings`
Fetching podspec for `React-RCTText` from `../node_modules/react-native/Libraries/Text`
Fetching podspec for `React-RCTVibration` from `../node_modules/react-native/Libraries/Vibration`
Fetching podspec for `React-RCTWebSocket` from `../node_modules/react-native/Libraries/WebSocket`
Fetching podspec for `React-cxxreact` from `../node_modules/react-native/ReactCommon/cxxreact`
Fetching podspec for `React-jsi` from `../node_modules/react-native/ReactCommon/jsi`
Fetching podspec for `React-jsiexecutor` from `../node_modules/react-native/ReactCommon/jsiexecutor`
Fetching podspec for `React-jsinspector` from `../node_modules/react-native/ReactCommon/jsinspector`
Fetching podspec for `UMBarCodeScannerInterface` from `../node_modules/unimodules-barcode-scanner-interface/ios`
Fetching podspec for `UMCameraInterface` from `../node_modules/unimodules-camera-interface/ios`
Fetching podspec for `UMConstantsInterface` from `../node_modules/unimodules-constants-interface/ios`
Fetching podspec for `UMCore` from `../node_modules/@unimodules/core/ios`
Fetching podspec for `UMFaceDetectorInterface` from `../node_modules/unimodules-face-detector-interface/ios`
Fetching podspec for `UMFileSystemInterface` from `../node_modules/unimodules-file-system-interface/ios`
Fetching podspec for `UMFontInterface` from `../node_modules/unimodules-font-interface/ios`
Fetching podspec for `UMImageLoaderInterface` from `../node_modules/unimodules-image-loader-interface/ios`
Fetching podspec for `UMPermissionsInterface` from `../node_modules/unimodules-permissions-interface/ios`
Fetching podspec for `UMReactNativeAdapter` from `../node_modules/@unimodules/react-native-adapter/ios`
Fetching podspec for `UMSensorsInterface` from `../node_modules/unimodules-sensors-interface/ios`
Fetching podspec for `UMTaskManagerInterface` from `../node_modules/unimodules-task-manager-interface/ios`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "UMTaskManagerInterface":
  In Podfile:
    UMTaskManagerInterface (from `../node_modules/unimodules-task-manager-interface/ios`)

Specs satisfying the `UMTaskManagerInterface (from `../node_modules/unimodules-task-manager-interface/ios`)` dependency were found, but they required a higher minimum deployment target.</pre>
</details>
<details>
  <summary>react-native info</summary>
  <pre>$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 9.53 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1</pre>
</details>

### My Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'Example' do
  # Pods for Example
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
  use_unimodules!
end

target 'Example-tvOS' do
  # Pods for Example-tvOS

  target 'Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by lucianomlima** [comment]
The example app above uses react native v0.60.5
I try with the latest v0.59 and works fine.

**Comment by pvinis** [comment]
try to change the first line to `platform :ios, '10.0'`. I guess unimodules don't support 9.

**Comment by sjchmiela** [comment]
@pvinis's suggestion is correct. Unimodules support iOS 10+ and Android 5+. 🙂

**Comment by lucianomlima** [comment]
Thanks!

**Comment by iamcxa** [comment]
just solved the problem and found here has a related issue. I think this should be documented at readme.

**Comment by yuukiii** [comment]
I agree because everyone reads the README.
