### ISSUE TITLE
Native dependencies not linked in 0.60+

### ISSUE THREAD

**Issue by Baterka** [unimodules/react-native-unimodules#75]
I am getting error when I try to run clean installation on Android:

> The method or property expo-file-system.readDirectoryAsync is not available on android, are you sure you've linked all the native dependencies properly?

,when I am trying to use `react-native-unimodules` (FileSystem) in clean `react-native` project. I installed it by `react-native-cli` and then installed `react-native-unimodules` by `yarn add`.

Seems that automatic linking not works?

yarn: 1.19.0
react-native-unimodules: ^0.7.0-rc.1
react-native: 0.61.1

**Comment by sjchmiela** [comment]
Automatic linking in unimodules' context means that unimodules are automatically linked to the project, not that `react-native-unimodules` is supported by `react-native` autolinking introduced in 0.60. This is because unimodules integrate deeper with app's code than regular RN modules, allowing 3rd party developers to provide modules that are easier to install (imagine only one `add this to onCreate()` instead of one per every installed native module).

To configure your app to use `react-native-unimodules` you'll need to follow setup instructions listed in https://github.com/unimodules/react-native-unimodules#-configure-ios and https://github.com/unimodules/react-native-unimodules#-configure-android.

**Comment by Baterka** [comment]
Same error after configuring gradle files...

**Comment by tmaly1980** [comment]
I've followed the iOS setup guide and when the app loads, I get a red/black screen error: 

`Cannot read property 'viewManagersNames' of undefined`

What am I missing? There's nothing related to unimodules listed in my NativeModules object.

**Comment by sjchmiela** [comment]
1. Have you edited `AppDelegate` so it looks similar to https://gist.github.com/brentvatne/1ece8c32a3c5c9d0ac3a470460c65603? The most important lines are
```objc
// adding RCTBridgeDelegate interface to AppDelegate.h
@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
```
```objc
// creating RCTBridge with self set as delegate
RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
```
```objc
// creating RCTRootView with this specific bridge
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"__YOUR_APP_NAME_HERE__" initialProperties:nil];
```
```objc
// adding extraModulesForBridge: method
- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // You can inject any extra modules that you would like here, more information at:
  // https://facebook.github.io/react-native/docs/native-modules-ios.html#dependency-injection
  return extraModules;
}
```
apart from adding the `_moduleRegistryAdapter` instance variable to `AppDelegate`.
2. Maybe you're using some version of `react-native-navigation`, which changes the way the bridge and root views are created? Then you'd need to hook into its setup.

**Comment by tmaly1980** [comment]
OK Thanks, I finally got it working. Good god, that was frustrating. 

The documentation isn't clear, and there's so much in that AppDelegate.m that I'm unclear about, so without exact lines mentioned, I wasn't sure what made a difference. Here's what I came up with (changes marked with arrows)
```

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]]; // <!-- ADD
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions]; // <!-- ADD

  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"AppName" initialProperties:nil]; // <!-- ADD, NO initWithBundleURL, moved to sourceURLForBridge

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;

  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}

 // <!-- ADD EVERYTHING BELOW
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
  #ifdef DEBUG
      return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
      // works in both simulator AND connected phone on network via IP
  #else
      // return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
      return [CodePush bundleURL]; // <!-- This version since I'm using CodePush
  #endif
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // You can inject any extra modules that you would like here, more information at:
  // https://facebook.github.io/react-native/docs/native-modules-ios.html#dependency-injection
  return extraModules;
}

@end

```

**Comment by Chandara-97** [comment]
Hi there !! I got this error:
"Could not load RNOneSignal native module. Make sure native dependencies are properly linked."
My react native(CLI): 
 "react-native": "0.66.1",
