### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke interface method 'void org.unimodules.interfaces.taskManager.TaskServiceInterface.setTaskManager(org.unimodules.interfaces.taskManager.TaskManagerInterface, java.lang.String, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by Luckygirlllll** [unimodules/react-native-unimodules#76]
Getting an error`: " java.lang.NullPointerException: Attempt to invoke interface method 'void org.unimodules.interfaces.taskManager.TaskServiceInterface.setTaskManager(org.unimodules.interfaces.taskManager.TaskManagerInterface, java.lang.String, java.lang.String)' `on a null object reference", when trying to run app on Android, expo sdk 35, bare workflow.

**Comment by sjchmiela** [comment]
And are you trying to use `expo-task-manager`?

**Comment by Luckygirlllll** [comment]
@sjchmiela yes

**Comment by sjchmiela** [comment]
Then there's going to be a problem, since, unfortunately, `expo-task-manager` is not yet supported in bare workflow. Information about that [can be found in the documentation](https://docs.expo.io/versions/v35.0.0/sdk/task-manager/#installation). 😞

**Comment by Luckygirlllll** [comment]
oh, I see, got it!

**Comment by roei133** [comment]
I did "expo eject" with bare and now I got the same error and i don't know how to fix it.
help, please.

**Comment by sonytooo** [comment]
Now, "expo-task-manager" is supported in the bare workflow. I've installed the expo-task-manager from the master branch (version - 8.1.0) in bare workflow. I've updated the "unimodules" to 0.8.0 and the version of unimodules-task-manager-interface is 5.1.0. I've used this documentation and everything seems to work well on iOS, yet this error remains unfixed on Android. Any idea for additional steps to fix this issue on Android or how at least to hide the error without using the "expo-task-manager" functionality until there is better documentation?

**Comment by jakecr** [comment]
I'm still having this issue. My expo app ran fine on ios but it would crash without an error message on android, so I converted it to a bare react-native app and now I am getting this error on my Android emulator. 
"
Attempt to invoke interface method 'voidorg.unimodules.interfaces.taskManager.TaskServicesInterface.setTaskManager(org.unimodules.interfaces.taskManager.TaskManagerInterface,jaka.lang.String, java.lang.String)' on null object reference
"
Any solutions?

**Comment by littlehome-eugene** [comment]
https://github.com/expo/expo/issues/3453 says it's now possible. but not sure how..

**Comment by hussainahmad** [comment]
@littlehome-eugene how you removed this error? As I m also getting this error .  I am using this in bare workflow app as it is now supported.  

![Screenshot_20200401-170626_Hello App Display Name](https://user-images.githubusercontent.com/5903522/78136310-d1816780-743c-11ea-8ce8-5f731ab2753a.jpg)

**Comment by sjchmiela** [comment]
`expo-task-manager` has been upgraded to support bare workflow just now. In order to be able to use it in bare worflow, ensure that:

- you're on latest version (`^8.1.0`)
- when instantiating `ReactModuleRegistryProvider` in `MainApplication` you do not pass in an empty array as the second argument.

**Comment by hussainahmad** [comment]
@sjchmiela Thanks for the early response. 
- I m using the latest version of  `expo-task-manager:^8.1.0`  and also updated version `react-native-unimodules:^0.8.1`.
-  Instantiating `ReactModuleRegistryProvider ` as described here [chnages in MainApplication.java](https://gist.github.com/brentvatne/62a9c949aa7d1cda410adbe01cba0554/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa) as per the documentation I am passing ` Arrays.<SingletonModule>asList()` as a second argument.

**Comment by sjchmiela** [comment]
I'm sorry for the confusion, latest documentation recommends passing `null` as the second argument ([1](https://gist.github.com/mczernek/0670ec16ca6071796853a66d589b49a5/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa0), [2](https://gist.github.com/mczernek/9de9e184abc430e9e3508d26738c8a14/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa)). Try it! 🙂

**Comment by hussainahmad** [comment]
Thanks mate. Resolved

**Comment by PierreSachot** [comment]
Hi,

I did the fix presented by @sjchmiela and @hussainahmad , this does not work for me, the null object reference continue to happen, what can I do ?

Thanks.

**Comment by littlehome-eugene** [comment]
@PierreSachot try to clean build, that worked for me

**Comment by hadpro24** [comment]
> I'm sorry for the confusion, latest documentation recommends passing `null` as the second argument ([1](https://gist.github.com/mczernek/0670ec16ca6071796853a66d589b49a5/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa0), [2](https://gist.github.com/mczernek/9de9e184abc430e9e3508d26738c8a14/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa)). Try it!

It not work for me. Do you have other alternative thanks.

**Comment by hadpro24** [comment]
> I'm sorry for the confusion, latest documentation recommends passing `null` as the second argument ([1](https://gist.github.com/mczernek/0670ec16ca6071796853a66d589b49a5/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa0), [2](https://gist.github.com/mczernek/9de9e184abc430e9e3508d26738c8a14/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa)). Try it!

Now I have other error : Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

**Comment by ezos86** [comment]
> I'm sorry for the confusion, latest documentation recommends passing `null` as the second argument ([1](https://gist.github.com/mczernek/0670ec16ca6071796853a66d589b49a5/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa0), [2](https://gist.github.com/mczernek/9de9e184abc430e9e3508d26738c8a14/revisions#diff-a2e7ff8a82f1c4be06f8b8163f2afefa)). Try it! 🙂

did not fix it for me. this method doesn't have an argument.

**Comment by ezos86** [comment]
> * 0.8.1

Adding the unimodules to 8.1 broke my build, it could not then find any of the packages.

**Comment by haibert** [comment]
Im getting this on a custom dev client, weird thing is it happened out of no where, I didn't even change anything.
