### ISSUE TITLE
Archive error IOS: library not found for -lReact 

### ISSUE THREAD

**Issue by Luckygirlllll** [unimodules/react-native-unimodules#77]
I have expo project ejected to bare workflow, when I'm trying to make IOS archive, I'm getting an error: "library not found for -lReact ", in react-native GitHub I got an answer that I need to upgrade react-native to the latest version, so my question is whether or not react-native-unimodules will work with the latest react-native version? or it will support only 0.59.10 version now?

**Comment by Luckygirlllll** [comment]
Here is my issue opened in react-native Github: https://github.com/facebook/react-native/issues/26785

**Comment by sjchmiela** [comment]
This comment should help you fix the issue. 🙂  https://github.com/facebook/react-native/issues/26785#issuecomment-546941326

**Comment by Luckygirlllll** [comment]
@sjchmiela yeah, sending me to my own issue is very helpful, especially according to the fact that I have RN 0.59.10

**Comment by sjchmiela** [comment]
Maybe I should have rephrased it to "I see a comment that should have helped you fix your issue in the other thread". Sorry for the misunderstanding.
