### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by blntylmn** [unimodules/react-native-unimodules#8]
Build failing with this exception:
`* Where:
Script '/Users/catsoft/Desktop/duello/mobile/node_modules/react-native-unimodules/gradle.groovy' line: 102`
`Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Map()`

**Comment by Sukumar-Abhijeet** [comment]
Any progress to the error , i am facing the same issue

**Comment by sjchmiela** [comment]
Try passing `new Map()` as an argument, instead of `[]`. 🤔

`expo-location` requires unimodules’ core and adapter, and `react-native-unimodules` is the easiest way to integrate it into a RN app. 🙃

**Comment by Sukumar-Abhijeet** [comment]
tried to replace the [] with newMap() , but it says "cannot create an instance from the abstract interface ...."

node_modules\react-native-unimodules\gradle.groovy': 102: You cannot create an instance from the abstract interface 'java.util.Map'.
   @ line 102, column 47.
     dules = { Map customOptions = new Map()-


MY CODE:
ext.includeUnimodules = { Map customOptions = new Map()->
  def options = [
    modulesPaths: ['../node_modules'],
    target: 'react-native',
    exclude: [],
  ] << customOptions

  def unimodules = findUnimodules(options.target, options.exclude, options.modulesPaths).unimodules

  for (unimodule in unimodules) {
    def config = unimodule.config
    def subdirectory = config.subdirectory

    include ":${unimodule.name}"
    project(":${unimodule.name}").projectDir = new File(unimodule.directory, subdirectory)
  }
}

**Comment by sjchmiela** [comment]
Oh shoot, how about `new HashMap()`?

**Comment by Sukumar-Abhijeet** [comment]
Thanks Man , That did sort out the problem , but a new problem is arising ..

FAILURE: Build failed with an exception.

* Where:
Script 'E:\........\myprojectname\node_modules\react-native-unimodules\gradle.groovy' line: 19

* What went wrong:
A problem occurred evaluating settings 'android'.
> E:\........\myprojectname\android\node_modules does not exist.

why is it searching node_modules inside android folder ??

and line 19  code is 
 def moduleConfigPaths = new FileNameFinder().getFileNames(baseDir, '**/unimodule.json', '')

**Comment by reinhardholl** [comment]
Experiencing exactly the same issue :(

**Comment by sjchmiela** [comment]
Could you try following this instruction item from the README:

> - If you need to customize the path to node_modules, for example because you are using yarn workspaces, then you can pass in a param modulesPaths for both of these functions: `includeUnimodules([modulesPaths: ['./path/to/node_modules']])`, `useUnimodules([modulesPaths: ['./path/to/node_modules']])`

and customize the path to `node_modules`? Try using `useUnimodules(modulesPaths: ['../../node_modules'])` in `app/build.gradle` and `includeUnimodules([modulePaths: ['../node_modules'])` in `settings.gradle`.

**Comment by reinhardholl** [comment]
Not working for me @sjchmiela

**Comment by sjchmiela** [comment]
Would you care to create a repro repository? I would try to tinker around and fix this 🙂

**Comment by Sukumar-Abhijeet** [comment]
Not working for me @sjchmiela .
Can i get another way of contact to you ?? i have things to ask on this

**Comment by Sukumar-Abhijeet** [comment]
I have created a repo 
https://github.com/Sukumar-Abhijeet/uniomduleIntegration
check it  
have just build an RN app and tried to install react-native-unimodule to it

**Comment by sjchmiela** [comment]
The following changes fixed syncing the repro project:
```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 0a9897f..a881b55 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -138,7 +138,9 @@ android {
 }
 
 dependencies {
-    useUnimodules()
+    useUnimodules([
+            modulesPaths: ['../../node_modules']
+    ])
     implementation fileTree(dir: "libs", include: ["*.jar"])
     implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
     implementation "com.facebook.react:react-native:+"  // From node_modules
diff --git a/android/settings.gradle b/android/settings.gradle
index 47449f4..b218e96 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -1,5 +1,7 @@
 apply from: '../node_modules/react-native-unimodules/gradle.groovy'
-includeUnimodules()
+includeUnimodules([
+        modulesPaths: ['../../node_modules']
+])
 rootProject.name = 'unimoduleIntegration'
 
 include ':app'
```

**Comment by reinhardholl** [comment]
Awesome! Will you be publishing a new version to npm?

**Comment by sjchmiela** [comment]
Aye! Soon. 🙂
