### ISSUE TITLE
Will this package work on 0.61.4 react native version?

### ISSUE THREAD

**Issue by Kailash23** [unimodules/react-native-unimodules#85]
I am converting my RN app having expo managed workflow to normal RN workflow (with RN Cli ). I am trying to reuse most of my code. So I have to use this package, but I am not sure will this work on the latest RN version.

**Comment by sjchmiela** [comment]
There is no reason for why it shouldn't!

**Comment by Kailash23** [comment]
https://www.npmjs.com/package/react-native-unimodules

Note: react-native-unimodules are not compatible with React Native 0.60.x yet.

It's written there. So I thought I should ask again.

**Comment by sjchmiela** [comment]
Ah true. Try using `react-native-unimodules@0.7.0-rc.4` — it should with with latest RN.

**Comment by Maddumage** [comment]
@sjchmiela I am facing the same issue with React Native version 0.61.4. I tried using  react-native-unimodules@0.7.0-rc.4 and faced the same issue.  Please Help

**Comment by sjchmiela** [comment]
Hey, @Maddumage. You haven't mentioned what issue are you facing and haven't provided any details. Could you please submit a new issue with all the details?

**Comment by lucaspelloni2** [comment]
I get this error here: 

```
 The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly

TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')

 Unhandled JS Exception: TypeError: null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')

Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

I cannot run my app anymore..

**Comment by sjchmiela** [comment]
Well, have you followed all the setup instructions from https://github.com/unimodules/react-native-unimodules#-installation? It doesn't look like so. 😕

Please, let's move the discussion off to another issue — your problem isn't related to `react-native-unimodules` working or not with RN@0.61.4.

**Comment by nikechanhk** [comment]
> Ah true. Try using `react-native-unimodules@0.7.0-rc.4` — it should with with latest RN.

You save my life. Thx a lots

**Comment by amahh014** [comment]
```
BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/nizammamedov/Desktop/dentalApp/dentApp/android/app/src/main/java/com/dentapp/MainApplication.java:19: error: cannot find symbol
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());
                                                                                                                                              ^
  symbol:   variable Arrays
  location: class MainApplication
/Users/nizammamedov/Desktop/dentalApp/dentApp/android/app/src/main/java/com/dentapp/MainApplication.java:36: error: cannot find symbol
          List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
                                          ^
  symbol: variable Arrays
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

How to solve this issue?
Please help

**Comment by duytq94** [comment]
I followed the instruction but stuck in this error:
https://github.com/unimodules/react-native-unimodules/issues/89#issuecomment-560247115

**Comment by sezginriggs** [comment]
0.8.0 version with RN 0.61.4 unfortunately leads to error when building for Android.  https://github.com/unimodules/react-native-unimodules/issues/122

**Comment by brentvatne** [comment]
if you initialize a new project with expo-cli it uses the latest 0.61 patch version
