### ISSUE TITLE
Npm install not working as expected

### ISSUE THREAD

**Issue by blntylmn** [unimodules/react-native-unimodules#9]
`npm i  react-native-unimodules` or `yarn add react-native-unimodules` adds a `react-native-unimodules `folder  under `node_modules` with only a `package.json` file in it.

only this working
`yarn add https://github.com/unimodules/react-native-unimodules#5adfeff1fd856febb31b7ac06436a822ed147a83`

**Comment by rach-m** [comment]
Having the exact same issue on a brand new React Native project

**Comment by brentvatne** [comment]
cc @tsapeta

**Comment by brentvatne** [comment]
looks like the package was renamed in readme a bit prematurely, we only had a pre-release version out. i tagged 0.1.0-rc.2 as the latest which should resolve it. sorry things are changing a bunch right now while we're still in preview, we're almost done with the biggest of the refactorings and it'll stabilize shortly

**Comment by rach-m** [comment]
Thank you for letting us know @brentvatne !

**Comment by tsapeta** [comment]
Yeah, we're now refactoring this part of code, `react-native-unimodules` is going to replace `@unimodules/core` package, however it's not yet released as final version. So for now, I'd recommend to use `@unimodules/core` instead. You can find its readme and installation guide on the npm registry: https://www.npmjs.com/package/@unimodules/core
