### ISSUE TITLE
Does this support expo-three?

### ISSUE THREAD

**Issue by timnlupo** [unimodules/react-native-unimodules#90]
Does this library support `expo-three`? I see no mention of it under the supported Expo APIs. It does support `expo-gl` and since I don't need AR, was hoping it would work.

I've done some testing on an [issue in the expo-three repo](https://github.com/expo/expo-three/issues/148) and notice THREE.js works if I save and update with live reload, but not if I reload using `⌘R`. Since it seems to be working besides that peculiar bug, I'm not sure if this is a me issue or an incompatibility issue. Any help would be appreciated. Thanks.

**Comment by sjchmiela** [comment]
As far as I know `expo-three` is just a helper library for easier integration with `Three.js` (so it doesn't have any native code and isn't a unimodule and thus — it's working or not working isn't in scope of `react-native-unimodules`). `Three.js` in turn is a helper library for GL. In Expo context, the GL backend that we support is `expo-gl`.

The issue you've described would better belong to `expo-gl` package (so `expo` repo). I can move it there if you want and assign appropriate people.

But first let me know if https://github.com/expo/expo-three/issues/148#issuecomment-559286867 means that the issue could be closed? 🙂

**Comment by timnlupo** [comment]
Yes! Thank you for the help.
