### ISSUE TITLE
[EXImagePicker] No known instance method for selector 'hasGrantedPermission:'

### ISSUE THREAD

**Issue by SCasarotto** [unimodules/react-native-unimodules#94]
After upgrading `react-native-unimodules` from `0.7.0-rc.4` to `0.7.0` and doing a `pod update` I am receiving the following error:

![image](https://user-images.githubusercontent.com/13336976/70102310-b412cd00-1605-11ea-84ac-041589e562b0.png)

Let me know if I can provide any additional details to help triage.

**Comment by lukmccall** [comment]
Hi @SCasarotto, did you also upgrade `expo-image-picker` to `8.0.0`?
If not please do this. The New version of `react-native-unimodules`  isn't compatible with older expo packages which are using permissions module.

**Comment by SCasarotto** [comment]
When I `expo install expo-image-picker` it keeps returning `7.0.0`. What am I missing to upgrade to `8.0.0`?

**Comment by SCasarotto** [comment]
Manually upgrading to v8 did allow me to build. Thank you for the help @lukmccall !
